### ISSUE TITLE
Markdown example does not work with myst_parser>=0.18

### ISSUE THREAD

**Issue by Alexboiboi** [widgetti/reacton#3]
The example from https://github.com/widgetti/reacton#markdown-component-example does not work with `myst_parser>=0.18`  since the `to_html` function has been removed from the python api (see https://github.com/executablebooks/MyST-Parser/blob/28725fceb8e1e117cb247b06a267f82c501ce527/CHANGELOG.md#breaking-changes)

One solution:

```python
@reacton.component
def Markdown(md: str):
    from markdown_it.renderer import RendererHTML
    from myst_parser.config.main import MdParserConfig
    from myst_parser.parsers.mdit import create_md_parser
    md_parser = create_md_parser(MdParserConfig(), RendererHTML)
    html = md_parser.render(md)
    return w.HTML(value=html)
```

BR, Alex

**Comment by maartenbreddels** [comment]
(FYI, sorry for the late reply, just noticed I didn't get GH notifications from the repo)

I just fixed this in https://github.com/widgetti/reacton/commit/af8b6e0291985fc2a080717a911f8b0648282071 , and also included a Markdown example at:

[Markdown example live with Jupyter lite](./_output/lab/index.html?path=markdown.ipynb)
     ![Markdown component and editor](https://user-images.githubusercontent.com/1765949/207259602-e671087f-67bf-41b3-81ee-27730c0693df.gif)
