### ISSUE TITLE
jupyterlite demo - `No module named 'reacton'`

### ISSUE THREAD

**Issue by jgunstone** [widgetti/reacton#5]
just a quick note to say the demo isn't working. 

otherwise looks great! can't wait to try it out

![image](https://user-images.githubusercontent.com/21370980/194372810-71d0340f-9102-4f97-b6d4-be1127d96463.png)

**Comment by jgunstone** [comment]
just tried this again and its working

**Comment by maartenbreddels** [comment]
Thanks, could be the cache that caused that.
