### ISSUE TITLE
minor correction in docs

### ISSUE THREAD

**Issue by mattkeanny** [widgetti/reacton#8]
Started exploring the project, no react knowledge, I like the pure python approach. 
Just a minor thing:
In the getting-started.md the example says:
```
el = ButtonClick
display(el)
```
I guess this was meant "()":
```
el = ButtonClick()
display(el)
```
Thanks a ton.

**Comment by maartenbreddels** [comment]
Hi there,

thanks, this is fixed now!

Regards,

Maarten Breddels
